on:
  push:
    tags:
      - 'v*.*.*'
      - 'b*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Site
        run: |
          npm ci
          env
          npm run ${{ (startsWith( github.ref_name, 'b' ) && 'build-dev') || 'build' }}
          cp LICENSE build

      - name: Pack build output
        run: |
          cd build
          tar -czvf ../build.tar.gz * --owner=0 --group=0 --mode=777

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: build.tar.gz
          generate_release_notes: true
          prerelease: ${{ startsWith( github.ref_name, 'b' ) }}
